### ISSUE TITLE
为啥release里的代码和网页里看到的代码不同呀

### ISSUE THREAD

**Issue by Heeteve** [Heeteve/HardwarePractice#2]
为啥release里的代码和网页里看到的代码不同呀

_Originally posted by @inamotto in https://github.com/Heeteve/HardwarePractice/issues/1#issuecomment-2559802340_

**Comment by Heeteve** [comment]
@inamotto release里的是验收时使用的版本，之后只补充了注释，修改了部分变量名，并没有功能/逻辑上的改动。

**Comment by inamotto** [comment]
好的谢谢学长😘
